name: BIOMI-RPI-IMAGE-BUILDER

on:
  workflow_dispatch:
    inputs:
      distro_name:
        description: "Raspberry OS remote image name (ex: bookworm)"
        required: true
      distro_folder:
        description: "Raspberry OS remote folder (generally a date, ex: 2024-10-28)"
        required: true
      distro_date:
        description: "Raspberry OS remote image date (prefix for the image name, ex: 2024-10-22 for 2024-10-22-raspios-bookworm-arm64-lite.img.xz)"
        required: true

env:
  IMAGE_NAME: ghcr.io/prismprotocolhub/biomi-rpi-image-builder

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Free up disk space on GitHub runner
        uses: jlumbroso/free-disk-space@main
        with:
          tool-cache: false

      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v4
        with:
          push: true
          platforms: |
            linux/amd64
            linux/arm64
          build-args: |
            DISTRO_DATE_FOLDER=${{ inputs.distro_folder }}
            DISTRO_DATE=${{ inputs.distro_date }}
            DISTRO_NAME=${{ inputs.distro_name }}
          tags: |
            ghcr.io/prismprotocolhub/biomi-rpi-image-builder:${{ inputs.distro_name }}-${{ inputs.distro_date }}
            ghcr.io/prismprotocolhub/biomi-rpi-image-builder:${{ github.sha }}

      - name: Create container from image
        run: docker create --name biomi-rpi-image-builder-container ghcr.io/prismprotocolhub/biomi-rpi-image-builder:${{ github.sha }}

      - name: Copy artifact from container
        run: docker cp biomi-rpi-image-builder-container:/build/raspios.qcow2.gz /tmp/raspios.qcow2.gz

      - name: Remove container
        run: docker rm biomi-rpi-image-builder-container

      - name: Create Release raspios-${{ inputs.distro_name }}-${{ inputs.distro_date }}
        uses: softprops/action-gh-release@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          tag_name: ${{ inputs.distro_name }}-${{ inputs.distro_date }}
          files: |
            /tmp/raspios.qcow2.gz
